### PR TITLE
fixing deprecation warnings for pytest

### PR DESCRIPTION
**Pull request by flowolf**
fixes some deprecation warnings when running tests with pytest. 

`python3 ./run_tests.py` still works as expected.

### CODE REVIEW

**Comment by Ppjet6** [comment]
Does `self.assertTrue` really do the same thing as both `self.failUnless` _and_ `self.failUnlessEqual`?

`failUnless` seems to be taking a comment as second parameter, while `failUnlessEqual` takes a value to compare to. I assume replacing the latter with `assertTrue` will now check the first parameter for truthiness.

**Comment by flowolf** [comment]
according to [the docs](https://docs.python.org/2/library/unittest.html#deprecated-aliases) the replaced method names are deprecated.

**Comment by flowolf** [comment]
but yes. going through it again, there are errors. Sorry about that. I fixed the mis-replacements.

**Comment by Ppjet6** [comment]
LGTM!

**Comment by linkmauve** [comment]
This has been merged upstream, thanks.

**Pull request closed without merging**
