### PR TITLE
Fix for TypeError: 'NoneType' object is not an iterator

### PR DESCRIPTION
**Pull request by jheling**
This is a fix for the Nonetype error that only seems to be appearing in Home Assistant. 
Fixes issue https://lab.louiz.org/poezio/slixmpp/issues/3429
It is also a fix for: https://github.com/jheling/freeathome/issues/27

### CODE REVIEW

**Comment by mathieui** [comment]
Thanks, this has been integrated (with some changes) into the repository: https://lab.louiz.org/poezio/slixmpp/-/merge_requests/39

**Comment by thundergreen** [comment]
great news!

**Comment by ksya** [comment]
This works great and solves a lot of issues for the plugin I maintain for Home Assistant: https://github.com/ksya/ha-nefiteasy/issues/20#issuecomment-616444288

Is it possible to make a new release for slixmpp including this fix?

**Comment by mathieui** [comment]
We have made a slixmpp 1.5.0 release today with the fix included, it is on pypi! (the script reposting the code to github from our gitlab is out for now so it doesn’t show up here)

**Pull request closed without merging**
